name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *' # runs daily at midnight
  workflow_dispatch: # allows manual run

jobs:
  generate-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Top Languages Stats
        run: |
          curl -o top-langs.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=BeatriceNakabanda&layout=compact&theme=tokyonight&token=${{ secrets.GH_TOKEN }}"

      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add top-langs.svg
          git commit -m "Update GitHub top languages" || echo "No changes to commit"
          git push
